global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/rules/*.yml

alerting:
  alertmanagers:
    - path_prefix: /alertmanager
      static_configs:
        - targets:
            - alertmanager-prod:9093

scrape_configs:
  - job_name: hub-api-prod
    metrics_path: /metrics
    basic_auth:
      username: metrics
      password_file: /etc/prometheus/api_read_key
    static_configs:
      - targets:
          - hub-api-prod:8000
